name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.4.2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build and test
        run: npm run build && npm test

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**
          tag_name: v${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
            - Add feature A
            - Fix issue B
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
